DROP TABLE IF EXISTS users, mpa, film, genre, film_genre, film_like, friends, directors, film_directors, reviews, review_likes;

CREATE TABLE IF NOT EXISTS users
(
    id       integer generated by default as identity not null primary key,
    email    varchar(255) NOT NULL,
    login    varchar(255) NOT NULL,
    name     varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS mpa
(
    id          integer generated by default as identity not null primary key,
    name        varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film
(
    id           integer generated by default as identity not null primary key,
    name         varchar(255) NOT NULL,
    description  varchar(200),
    release_date date         NOT NULL,
    duration     int          NOT NULL,
    rating_id    integer      NOT NULL REFERENCES mpa(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS genre
(
    id   integer generated by default as identity not null primary key,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  integer REFERENCES film(id) ON DELETE CASCADE,
    genre_id integer REFERENCES genre(id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_like
(
    film_id  integer REFERENCES film(id) ON DELETE CASCADE,
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);


CREATE TABLE IF NOT EXISTS friends
(
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    friend_id integer REFERENCES users(id) ON DELETE CASCADE,
    status boolean
);

CREATE TABLE IF NOT EXISTS directors
(
    director_id integer generated by default as identity not null primary key,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors
(
    director_id integer REFERENCES directors(director_id) ON DELETE CASCADE,
    film_id integer REFERENCES film(id) ON DELETE CASCADE,
    PRIMARY KEY (director_id, film_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id integer generated by default as identity not null primary key,
    content VARCHAR(200) NOT NULL,
    is_positive BOOLEAN DEFAULT FALSE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    film_id INT NOT NULL REFERENCES film(id) ON DELETE CASCADE,
    useful INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id INT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    like_type varchar NOT NULL,
    PRIMARY KEY (review_id, user_id)
);